'use strict';
const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const safeUrl=s=>{try{let u=new URL(s);return u.protocol==='https:'?u.href:'#';}catch{return '#';}};
const anchor=(u,t)=>`<a href="${esc(safeUrl(u))}" target="_blank" rel="noopener noreferrer">${esc(t)}</a>`;
const vendors=['OpenAI','Anthropic','Google','xAI','DeepSeek','阿里千问','月之暗面 Kimi','智谱 GLM','字节豆包'];
let data,filter='全部';
function renderEvents(){let list=data.events.filter(e=>e.status!=='cancelled'&&(filter==='全部'||e.vendor===filter)&&`${e.model} ${e.summary}`.toLowerCase().includes($('search').value.toLowerCase())).sort((a,b)=>b.release_date.localeCompare(a.release_date));let year='';$('events').innerHTML=list.map(e=>{let label='';if(e.release_date.slice(0,4)!==year){year=e.release_date.slice(0,4);label=`<div class="year-label">${esc(year)}</div>`;}return label+`<article class="event"><div class="event-date">${esc(e.release_date.slice(5).replace('-','.'))}<small>${esc(year)}</small></div><div><h3>${esc(e.model)}</h3><p>${esc(e.summary)}</p><div class="meta"><span>${e.date_precision==='timestamp'?'已换算北京时间':'日期已核实 · 仅日精度'}</span><span title="${esc(e.date_note)}">${esc(e.date_note)}</span></div></div><div class="event-right"><span class="vendor-tag">${esc(e.vendor)}</span>${anchor(e.source_url,'查看来源 ↗')}</div></article>`;}).join('')||'<p class="muted">没有符合筛选条件的发布。</p>';}
async function init(){try{const r=await fetch('data.json',{cache:'no-cache'});if(!r.ok)throw new Error('数据暂时无法加载');data=await r.json();const base=data.config.base_url,repo=`https://github.com/${data.config.repository}`,feed=base+'/calendar.ics';$('feed-url').textContent=feed;$('apple').href=feed.replace(/^https:/,'webcal:');$('google').href='https://calendar.google.com/calendar/r?cid='+encodeURIComponent(feed);$('event-count').textContent=data.events.filter(e=>e.status!=='cancelled').length;$('history-note').textContent='2025 年起精选历史 · 持续补充';
for(const [id,path] of [['repo-link',''],['readme-link','#readme'],['service-link','/actions/workflows/service.yml'],['review-workflow','/actions/workflows/review.yml'],['actions-link','/actions/workflows/calendar.yml']])$(id).href=repo+path;
$('copy').onclick=async()=>{try{await navigator.clipboard.writeText(feed);$('copy-message').textContent='订阅地址已复制。请在日历中通过网址添加。';}catch{$('copy-message').textContent='请复制下方“订阅帮助”中的地址。';}};
$('filters').innerHTML=['全部',...vendors].map(v=>`<button class="filter ${v===filter?'active':''}" data-vendor="${esc(v)}" aria-pressed="${v===filter}">${esc(v)}</button>`).join('');$('filters').onclick=e=>{const b=e.target.closest('button');if(!b)return;filter=b.dataset.vendor;document.querySelectorAll('.filter').forEach(n=>{n.classList.toggle('active',n.dataset.vendor===filter);n.setAttribute('aria-pressed',String(n.dataset.vendor===filter));});renderEvents();};$('search').oninput=renderEvents;renderEvents();
const h=data.health,checked=h.checked_at?new Date(h.checked_at):null,stale=!checked||Date.now()-checked.getTime()>48*3600*1000;const failures=(h.sources||[]).filter(s=>s.status!=='ok');$('health-label').textContent=stale?'更新逾期':failures.length?'部分来源异常':'运行正常';$('last-check').textContent=checked?'最近检查 '+checked.toLocaleString('zh-CN',{timeZone:'Asia/Shanghai',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hour12:false}):'尚未完成首轮检查';$('status-note').textContent=stale?'距离上次检查已超过 48 小时，请检查 GitHub Actions。':failures.length?`${failures.length} 个入口存在异常或详情读取限制。可用入口仍继续检查；异常不会删除已有事件。`:'所有配置入口均已成功解析。';
$('sources').innerHTML=(h.sources||[]).map(s=>`<article class="source"><div class="source-top">${anchor(s.url,s.vendor||s.id)}<span class="badge ${s.status==='ok'?'':'warn'}">${s.status==='ok'?'● 正常':s.status==='degraded'?'◐ 部分受限':'○ 读取失败'}</span></div><small>${esc(s.id)} · ${s.official?'官方':'新闻发现'} · ${s.entries} 条入口记录</small>${s.errors?.length?`<small>${esc(s.errors[0]).slice(0,220)}</small>`:''}</article>`).join('');
$('pending-count').textContent=data.pending.length;$('pending').innerHTML=data.pending.map(c=>`<details><summary>${esc(c.model)} <span class="muted">· ${esc(c.vendor)} · ${esc(c.release_date||'日期待核实')} · 规则 ${c.score} 分</span></summary><p>候选 ID：<code>${esc(c.id)}</code></p><p>${esc(c.summary)}</p><ul>${c.reasons.map(r=>`<li>${esc(r)}</li>`).join('')}</ul><p>${anchor(c.source_url,'打开候选来源 ↗')}</p><p>在“审核工作流”中填入此 ID；批准前核实模型名、官方链接、发布日期、日期口径和里程碑理由。</p></details>`).join('')||'<p class="muted">当前没有待审核候选。</p>';
}catch(e){$('events').innerHTML=`<p class="error">${esc(e.message)}。可以直接使用订阅链接，或稍后刷新本页。</p>`;$('health-label').textContent='加载失败';}}
init();
